services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      # Default user and database will be created using `init-defaults.sh` script
      CLICKHOUSE_DB: r0
      CLICKHOUSE_USER: demouser
      CLICKHOUSE_PASSWORD: test@123
    hostname: clickhouse-0.localhost
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./docker/clickhouse/init-defaults.sh:/docker-entrypoint-initdb.d/init-defaults.sh:ro